---
# tasks file for registry
- name: Create namespace
  shell:
    cmd: 'kubectl create namespace {{ registry_namespace }}'
  become: true
  ignore_errors: true
- name: Ensure manifests folder exits
  file:
    path: '{{ manifest_folder }}'
    state: directory
- name: Render manifests
  template:
    src: '{{ item.src }}'
    dest: '{{ manifest_folder }}/{{ item.dest }}'
  with_items: '{{registry_manifests }}'
- name: Apply manifests
  shell:
    cmd: 'kubectl apply -f {{ manifest_folder }}/{{ item.dest }} -n {{ registry_namespace }}'
  with_items: '{{ registry_manifests }}'