apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: {{ registry_namespace }}
spec:
  rules:
    - host: registry.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  registry-service
                port:
                  number: 5000
 